name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: '19'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker image
      run: |
        echo "${GITHUB_SHA}" > VERSION
        docker build . --file Dockerfile --tag blackms/demo:${GITHUB_SHA}

    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker push blackms/demo:${GITHUB_SHA}

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Apply Kubernetes configuration
      run: |
        kubectl config set-context --current --namespace=default
        kubectl set image deployment/app-deployment demo-app=blackms/demo:${GITHUB_SHA}
