name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: '19'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag blackms/demo:latest

    - name: Push Docker image to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker push yourusername/yourrepository

    - name: Apply Kubernetes configuration
      run: |
        kubectl config set-context --current --namespace=default
        kubectl apply -f k8s-deployment.yml
